name: Daily test run

on:
  schedule:
    # 5 19 UTC = 00:05 AM PKT (UTC+5) every day
    - cron: "5 19 * * *"
  workflow_dispatch: {}   # allow manual trigger as well


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Run script
        env:
          SSM_TOKEN: ${{ secrets.SSM_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          WHATSAPP_TO_NUMBER: ${{ secrets.WHATSAPP_TO_NUMBER }}
        run: python main.py


      - name: Upload Video artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-video
          path: out
          if-no-files-found: ignore
