name: Session Monitor (realtime)

permissions:
  contents: write   # <--- add this

on:
# schedule now done from cloudfare (UTC)
  workflow_dispatch:         # allow manual run too, now triggered by cloudfare

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow "imageio[ffmpeg]" numpy


      - name: Run session monitor once
        env:
          SSM_TOKEN: ${{ secrets.SSM_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          WHATSAPP_TO_NUMBER: ${{ secrets.WHATSAPP_TO_NUMBER }}
        run: python session_monitor.py

      - name: Commit & push updated state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add session_state.json || true
          git commit -m "Update session state" || echo "No changes to commit"
          git push
